In [1]:
import numpy as np
import pandas as pd

In [2]:


from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv("demand_forecast_dataset_2015_2026.csv")

In [4]:
df

,Year,District,Population,Population_Growth_percent,Urbanization_rate,Per_Capita_Income,Avg_Mandi_Price,MSP,Price_Change_percent,Export_Quantity_tons,Import_Quantity_tons,Global_Price_Index,Processing_Industry_Demand,Govt_Procurement_Target,Total_Demand_tons
0,2015,Barmer,1200000,2.15,26.00,126754.98,1325.09,1275,11.94,5575.25,719.13,100.65,15675.67,1417.16,41331.47
1,2015,Jaisalmer,650000,1.91,26.06,113802.40,1542.69,1275,7.53,2153.30,491.95,147.61,5250.69,12281.47,36585.72
2,2015,Jodhpur,3200000,1.61,31.22,242726.22,1382.91,1275,-2.87,1225.37,685.62,134.24,56593.73,11216.25,162713.89
3,2015,Bikaner,2300000,2.75,40.14,173846.91,1634.25,1275,9.23,6962.80,483.01,140.80,19664.75,4190.58,74680.57
4,2015,Nagaur,3300000,1.14,34.31,97170.24,1353.02,1275,9.62,3236.24,327.64,108.62,36972.32,14113.16,144365.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2026,Agra,5658400,2.60,64.43,333012.37,2755.21,2900,-1.63,2137.24,448.44,136.85,84509.21,5235.07,293748.14
476,2026,Mathura,3049020,1.57,51.11,416383.16,3108.28,2900,16.70,4963.80,786.94,133.88,27659.03,1559.14,169708.38
477,2026,Firozabad,2975750,1.73,33.40,230120.17,3183.30,2900,7.62,1185.96,577.52,164.85,36634.27,18280.46,164426.66
478,2026,Mainpuri,2081160,1.42,56.39,260235.34,3124.03,2900,3.80,4437.49,458.84,154.56,28508.68,5089.25,88904.53
479,2026,Etawah,2068160,2.66,61.90,188019.03,3912.05,2900,10.41,1989.35,103.81,112.52,34447.42,10939.35,97878.18

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["District"] = le.fit_transform(df["District"])

In [6]:

df = df.drop("Year", axis=1)



x = df.drop("Total_Demand_tons", axis=1)
y = df["Total_Demand_tons"]

In [7]:
x

,District,Population,Population_Growth_percent,Urbanization_rate,Per_Capita_Income,Avg_Mandi_Price,MSP,Price_Change_percent,Export_Quantity_tons,Import_Quantity_tons,Global_Price_Index,Processing_Industry_Demand,Govt_Procurement_Target
0,5,1200000,2.15,26.00,126754.98,1325.09,1275,11.94,5575.25,719.13,100.65,15675.67,1417.16
1,14,650000,1.91,26.06,113802.40,1542.69,1275,7.53,2153.30,491.95,147.61,5250.69,12281.47
2,15,3200000,1.61,31.22,242726.22,1382.91,1275,-2.87,1225.37,685.62,134.24,56593.73,11216.25
3,7,2300000,2.75,40.14,173846.91,1634.25,1275,9.23,6962.80,483.01,140.80,19664.75,4190.58
4,22,3300000,1.14,34.31,97170.24,1353.02,1275,9.62,3236.24,327.64,108.62,36972.32,14113.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1,5658400,2.60,64.43,333012.37,2755.21,2900,-1.63,2137.24,448.44,136.85,84509.21,5235.07
476,21,3049020,1.57,51.11,416383.16,3108.28,2900,16.70,4963.80,786.94,133.88,27659.03,1559.14
477,11,2975750,1.73,33.40,230120.17,3183.30,2900,7.62,1185.96,577.52,164.85,36634.27,18280.46
478,20,2081160,1.42,56.39,260235.34,3124.03,2900,3.80,4437.49,458.84,154.56,28508.68,5089.25
479,10,2068160,2.66,61.90,188019.03,3912.05,2900,10.41,1989.35,103.81,112.52,34447.42,10939.35

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.1, random_state=42
)

In [10]:
gbr = GradientBoostingRegressor(
    n_estimators=100,       # number of trees
    learning_rate=0.1,      # step size
    max_depth=3,            # depth of each tree
    random_state=42
)

In [11]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [12]:
y_pred = gbr.predict(X_test)

In [13]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", np.sqrt(mse))
print("R2 Score:", r2)

MSE: 405794311.90473515
RMSE: 20144.336968605723
R2 Score: 0.8289661117682958

In [14]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=4
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [15]:
y_pred = model.predict(X_test)

In [16]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", np.sqrt(mse))
print("R2 Score:", r2)

MSE: 482130682.49739534
RMSE: 21957.474410719355
R2 Score: 0.7967919144152682

In [18]:
print(mse/np.sqrt(mse))

21957.47441071936